## H2 Configuration
spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /forum
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:forum;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true